// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/activity_entity.dart';
import 'models/author_profile_entity.dart';
import 'models/device_profile_entity.dart';
import 'models/diary_entity.dart';
import 'models/record_draft_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3014340625497478550),
    name: 'ActivityEntity',
    lastPropertyId: const obx_int.IdUid(12, 1109511130613721833),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4693112843845237037),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8664221998494237186),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 21500456046779489),
        name: 'time',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8818483730579662998),
        name: 'details',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4969781922129048019),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2147283445462106961),
        name: 'diaryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4296004632891135973),
        relationField: 'diary',
        relationTarget: 'DiaryEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3951416368719840019),
        name: 'timePrecision',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2383309938337246146),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7830290555750988587),
        name: 'createdByAuthorProfileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1284952037618883009),
        name: 'createdByDeviceProfileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7364008710423433252),
        name: 'lastModifiedByAuthorProfileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1109511130613721833),
        name: 'lastModifiedByDeviceProfileId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7784148166755830454),
    name: 'DiaryEntity',
    lastPropertyId: const obx_int.IdUid(13, 8483514328196674486),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4920149699993225483),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5934905229092552166),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7334882726399196966),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3139534169329158746),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6225454372744249316),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5901673729773360223),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 6229927242462545823),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1234567890123456789),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7610676040634885379),
        name: 'recordId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 4154334858951904683),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6204651566794506874),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1391307458252641105),
        name: 'createdByAuthorProfileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1756132609172896534),
        name: 'createdByDeviceProfileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3492742934748550029),
        name: 'lastModifiedByAuthorProfileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8483514328196674486),
        name: 'lastModifiedByDeviceProfileId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'activities',
        srcEntity: 'ActivityEntity',
        srcField: 'diary',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7267053488527556749),
    name: 'RecordDraftEntity',
    lastPropertyId: const obx_int.IdUid(10, 7546525739943859305),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 297220628326684676),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2039058292242704036),
        name: 'draftId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 3814644681440260711),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8347721301641903710),
        name: 'draftKind',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3237704710357051558),
        name: 'recordType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6911837752050715765),
        name: 'targetRecordId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 7756920370847829618),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 137211334806176683),
        name: 'payloadSchemaVersion',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 431416241111935843),
        name: 'fieldPayloadJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 9179149231182169138),
        name: 'baseLastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4103476853539093946),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7546525739943859305),
        name: 'lastSavedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8617128554070098313),
    name: 'AuthorProfileEntity',
    lastPropertyId: const obx_int.IdUid(6, 5500009732612843260),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8030750345486684197),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4540285916938291502),
        name: 'authorProfileId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 1419732821400451937),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1665940262561319247),
        name: 'nickname',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5391189275906388874),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6878555105160524880),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5500009732612843260),
        name: 'isCurrent',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7135689420437583296),
    name: 'DeviceProfileEntity',
    lastPropertyId: const obx_int.IdUid(5, 8613089406167071831),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1308888238229311538),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3026279456824822832),
        name: 'deviceProfileId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 5858733805991619695),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7698913700909905742),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1750248484477288279),
        name: 'isCurrent',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8613089406167071831),
        name: 'hasSharedHistory',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 7135689420437583296),
    lastIndexId: const obx_int.IdUid(7, 5858733805991619695),
    lastRelationId: const obx_int.IdUid(1, 6838825628405302824),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [6838825628405302824],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ActivityEntity: obx_int.EntityDefinition<ActivityEntity>(
      model: _entities[0],
      toOneRelations: (ActivityEntity object) => [object.diary],
      toManyRelations: (ActivityEntity object) => {},
      getId: (ActivityEntity object) => object.id,
      setId: (ActivityEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ActivityEntity object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final detailsOffset = fbb.writeString(object.details);
        final createdByAuthorProfileIdOffset =
            object.createdByAuthorProfileId == null
            ? null
            : fbb.writeString(object.createdByAuthorProfileId!);
        final createdByDeviceProfileIdOffset =
            object.createdByDeviceProfileId == null
            ? null
            : fbb.writeString(object.createdByDeviceProfileId!);
        final lastModifiedByAuthorProfileIdOffset =
            object.lastModifiedByAuthorProfileId == null
            ? null
            : fbb.writeString(object.lastModifiedByAuthorProfileId!);
        final lastModifiedByDeviceProfileIdOffset =
            object.lastModifiedByDeviceProfileId == null
            ? null
            : fbb.writeString(object.lastModifiedByDeviceProfileId!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addInt64(2, object.time.millisecondsSinceEpoch);
        fbb.addOffset(3, detailsOffset);
        fbb.addInt64(4, object.lastModified.millisecondsSinceEpoch);
        fbb.addInt64(5, object.diary.targetId);
        fbb.addInt64(6, object.timePrecision);
        fbb.addInt64(7, object.createdAt?.millisecondsSinceEpoch);
        fbb.addOffset(8, createdByAuthorProfileIdOffset);
        fbb.addOffset(9, createdByDeviceProfileIdOffset);
        fbb.addOffset(10, lastModifiedByAuthorProfileIdOffset);
        fbb.addOffset(11, lastModifiedByDeviceProfileIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final timePrecisionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final detailsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastModifiedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final createdByAuthorProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final createdByDeviceProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final lastModifiedByAuthorProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final lastModifiedByDeviceProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object = ActivityEntity(
          id: idParam,
          type: typeParam,
          time: timeParam,
          timePrecision: timePrecisionParam,
          details: detailsParam,
          lastModified: lastModifiedParam,
          createdAt: createdAtParam,
          createdByAuthorProfileId: createdByAuthorProfileIdParam,
          createdByDeviceProfileId: createdByDeviceProfileIdParam,
          lastModifiedByAuthorProfileId: lastModifiedByAuthorProfileIdParam,
          lastModifiedByDeviceProfileId: lastModifiedByDeviceProfileIdParam,
        );
        object.diary.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.diary.attach(store);
        return object;
      },
    ),
    DiaryEntity: obx_int.EntityDefinition<DiaryEntity>(
      model: _entities[1],
      toOneRelations: (DiaryEntity object) => [],
      toManyRelations: (DiaryEntity object) => {
        obx_int.RelInfo<ActivityEntity>.toOneBacklink(
          6,
          object.id,
          (ActivityEntity srcObject) => srcObject.diary,
        ): object.activities,
      },
      getId: (DiaryEntity object) => object.id,
      setId: (DiaryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DiaryEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final contentOffset = fbb.writeString(object.content);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final summaryOffset = fbb.writeString(object.summary);
        final recordIdOffset = object.recordId == null
            ? null
            : fbb.writeString(object.recordId!);
        final createdByAuthorProfileIdOffset =
            object.createdByAuthorProfileId == null
            ? null
            : fbb.writeString(object.createdByAuthorProfileId!);
        final createdByDeviceProfileIdOffset =
            object.createdByDeviceProfileId == null
            ? null
            : fbb.writeString(object.createdByDeviceProfileId!);
        final lastModifiedByAuthorProfileIdOffset =
            object.lastModifiedByAuthorProfileId == null
            ? null
            : fbb.writeString(object.lastModifiedByAuthorProfileId!);
        final lastModifiedByDeviceProfileIdOffset =
            object.lastModifiedByDeviceProfileId == null
            ? null
            : fbb.writeString(object.lastModifiedByDeviceProfileId!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addInt64(4, object.lastModified.millisecondsSinceEpoch);
        fbb.addOffset(5, embeddingOffset);
        fbb.addOffset(6, summaryOffset);
        fbb.addOffset(7, recordIdOffset);
        fbb.addInt64(8, object.createdAt?.millisecondsSinceEpoch);
        fbb.addOffset(9, createdByAuthorProfileIdOffset);
        fbb.addOffset(10, createdByDeviceProfileIdOffset);
        fbb.addOffset(11, lastModifiedByAuthorProfileIdOffset);
        fbb.addOffset(12, lastModifiedByDeviceProfileIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final recordIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastModifiedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final createdByAuthorProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final createdByDeviceProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final lastModifiedByAuthorProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final lastModifiedByDeviceProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = DiaryEntity(
          id: idParam,
          recordId: recordIdParam,
          date: dateParam,
          title: titleParam,
          summary: summaryParam,
          content: contentParam,
          lastModified: lastModifiedParam,
          createdAt: createdAtParam,
          createdByAuthorProfileId: createdByAuthorProfileIdParam,
          createdByDeviceProfileId: createdByDeviceProfileIdParam,
          lastModifiedByAuthorProfileId: lastModifiedByAuthorProfileIdParam,
          lastModifiedByDeviceProfileId: lastModifiedByDeviceProfileIdParam,
          embedding: embeddingParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<DiaryEntity>(
          object.activities,
          store,
          obx_int.RelInfo<ActivityEntity>.toOneBacklink(
            6,
            object.id,
            (ActivityEntity srcObject) => srcObject.diary,
          ),
        );
        return object;
      },
    ),
    RecordDraftEntity: obx_int.EntityDefinition<RecordDraftEntity>(
      model: _entities[2],
      toOneRelations: (RecordDraftEntity object) => [],
      toManyRelations: (RecordDraftEntity object) => {},
      getId: (RecordDraftEntity object) => object.id,
      setId: (RecordDraftEntity object, int id) {
        object.id = id;
      },
      objectToFB: (RecordDraftEntity object, fb.Builder fbb) {
        final draftIdOffset = fbb.writeString(object.draftId);
        final draftKindOffset = fbb.writeString(object.draftKind);
        final recordTypeOffset = fbb.writeString(object.recordType);
        final targetRecordIdOffset = object.targetRecordId == null
            ? null
            : fbb.writeString(object.targetRecordId!);
        final fieldPayloadJsonOffset = fbb.writeString(object.fieldPayloadJson);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, draftIdOffset);
        fbb.addOffset(2, draftKindOffset);
        fbb.addOffset(3, recordTypeOffset);
        fbb.addOffset(4, targetRecordIdOffset);
        fbb.addInt64(5, object.payloadSchemaVersion);
        fbb.addOffset(6, fieldPayloadJsonOffset);
        fbb.addInt64(7, object.baseLastModified?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.lastSavedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final baseLastModifiedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final draftIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final draftKindParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final recordTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final targetRecordIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final payloadSchemaVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final fieldPayloadJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final baseLastModifiedParam = baseLastModifiedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(baseLastModifiedValue);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final lastSavedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final object = RecordDraftEntity(
          id: idParam,
          draftId: draftIdParam,
          draftKind: draftKindParam,
          recordType: recordTypeParam,
          targetRecordId: targetRecordIdParam,
          payloadSchemaVersion: payloadSchemaVersionParam,
          fieldPayloadJson: fieldPayloadJsonParam,
          baseLastModified: baseLastModifiedParam,
          createdAt: createdAtParam,
          lastSavedAt: lastSavedAtParam,
        );

        return object;
      },
    ),
    AuthorProfileEntity: obx_int.EntityDefinition<AuthorProfileEntity>(
      model: _entities[3],
      toOneRelations: (AuthorProfileEntity object) => [],
      toManyRelations: (AuthorProfileEntity object) => {},
      getId: (AuthorProfileEntity object) => object.id,
      setId: (AuthorProfileEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AuthorProfileEntity object, fb.Builder fbb) {
        final authorProfileIdOffset = fbb.writeString(object.authorProfileId);
        final nicknameOffset = fbb.writeString(object.nickname);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, authorProfileIdOffset);
        fbb.addOffset(2, nicknameOffset);
        fbb.addInt64(3, object.colorValue);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addBool(5, object.isCurrent);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final authorProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nicknameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isCurrentParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = AuthorProfileEntity(
          id: idParam,
          authorProfileId: authorProfileIdParam,
          nickname: nicknameParam,
          colorValue: colorValueParam,
          createdAt: createdAtParam,
          isCurrent: isCurrentParam,
        );

        return object;
      },
    ),
    DeviceProfileEntity: obx_int.EntityDefinition<DeviceProfileEntity>(
      model: _entities[4],
      toOneRelations: (DeviceProfileEntity object) => [],
      toManyRelations: (DeviceProfileEntity object) => {},
      getId: (DeviceProfileEntity object) => object.id,
      setId: (DeviceProfileEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DeviceProfileEntity object, fb.Builder fbb) {
        final deviceProfileIdOffset = fbb.writeString(object.deviceProfileId);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceProfileIdOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addBool(3, object.isCurrent);
        fbb.addBool(4, object.hasSharedHistory);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final deviceProfileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final isCurrentParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final hasSharedHistoryParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = DeviceProfileEntity(
          id: idParam,
          deviceProfileId: deviceProfileIdParam,
          createdAt: createdAtParam,
          isCurrent: isCurrentParam,
          hasSharedHistory: hasSharedHistoryParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ActivityEntity] entity fields to define ObjectBox queries.
class ActivityEntity_ {
  /// See [ActivityEntity.id].
  static final id = obx.QueryIntegerProperty<ActivityEntity>(
    _entities[0].properties[0],
  );

  /// See [ActivityEntity.type].
  static final type = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[1],
  );

  /// See [ActivityEntity.time].
  static final time = obx.QueryDateProperty<ActivityEntity>(
    _entities[0].properties[2],
  );

  /// See [ActivityEntity.details].
  static final details = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[3],
  );

  /// See [ActivityEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<ActivityEntity>(
    _entities[0].properties[4],
  );

  /// See [ActivityEntity.diary].
  static final diary = obx.QueryRelationToOne<ActivityEntity, DiaryEntity>(
    _entities[0].properties[5],
  );

  /// See [ActivityEntity.timePrecision].
  static final timePrecision = obx.QueryIntegerProperty<ActivityEntity>(
    _entities[0].properties[6],
  );

  /// See [ActivityEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ActivityEntity>(
    _entities[0].properties[7],
  );

  /// See [ActivityEntity.createdByAuthorProfileId].
  static final createdByAuthorProfileId =
      obx.QueryStringProperty<ActivityEntity>(_entities[0].properties[8]);

  /// See [ActivityEntity.createdByDeviceProfileId].
  static final createdByDeviceProfileId =
      obx.QueryStringProperty<ActivityEntity>(_entities[0].properties[9]);

  /// See [ActivityEntity.lastModifiedByAuthorProfileId].
  static final lastModifiedByAuthorProfileId =
      obx.QueryStringProperty<ActivityEntity>(_entities[0].properties[10]);

  /// See [ActivityEntity.lastModifiedByDeviceProfileId].
  static final lastModifiedByDeviceProfileId =
      obx.QueryStringProperty<ActivityEntity>(_entities[0].properties[11]);
}

/// [DiaryEntity] entity fields to define ObjectBox queries.
class DiaryEntity_ {
  /// See [DiaryEntity.id].
  static final id = obx.QueryIntegerProperty<DiaryEntity>(
    _entities[1].properties[0],
  );

  /// See [DiaryEntity.date].
  static final date = obx.QueryDateProperty<DiaryEntity>(
    _entities[1].properties[1],
  );

  /// See [DiaryEntity.title].
  static final title = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[2],
  );

  /// See [DiaryEntity.content].
  static final content = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[3],
  );

  /// See [DiaryEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<DiaryEntity>(
    _entities[1].properties[4],
  );

  /// See [DiaryEntity.embedding].
  static final embedding = obx.QueryHnswProperty<DiaryEntity>(
    _entities[1].properties[5],
  );

  /// See [DiaryEntity.summary].
  static final summary = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[6],
  );

  /// See [DiaryEntity.recordId].
  static final recordId = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[7],
  );

  /// See [DiaryEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<DiaryEntity>(
    _entities[1].properties[8],
  );

  /// See [DiaryEntity.createdByAuthorProfileId].
  static final createdByAuthorProfileId = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[9],
  );

  /// See [DiaryEntity.createdByDeviceProfileId].
  static final createdByDeviceProfileId = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[10],
  );

  /// See [DiaryEntity.lastModifiedByAuthorProfileId].
  static final lastModifiedByAuthorProfileId =
      obx.QueryStringProperty<DiaryEntity>(_entities[1].properties[11]);

  /// See [DiaryEntity.lastModifiedByDeviceProfileId].
  static final lastModifiedByDeviceProfileId =
      obx.QueryStringProperty<DiaryEntity>(_entities[1].properties[12]);

  /// see [DiaryEntity.activities]
  static final activities =
      obx.QueryBacklinkToMany<ActivityEntity, DiaryEntity>(
        ActivityEntity_.diary,
      );
}

/// [RecordDraftEntity] entity fields to define ObjectBox queries.
class RecordDraftEntity_ {
  /// See [RecordDraftEntity.id].
  static final id = obx.QueryIntegerProperty<RecordDraftEntity>(
    _entities[2].properties[0],
  );

  /// See [RecordDraftEntity.draftId].
  static final draftId = obx.QueryStringProperty<RecordDraftEntity>(
    _entities[2].properties[1],
  );

  /// See [RecordDraftEntity.draftKind].
  static final draftKind = obx.QueryStringProperty<RecordDraftEntity>(
    _entities[2].properties[2],
  );

  /// See [RecordDraftEntity.recordType].
  static final recordType = obx.QueryStringProperty<RecordDraftEntity>(
    _entities[2].properties[3],
  );

  /// See [RecordDraftEntity.targetRecordId].
  static final targetRecordId = obx.QueryStringProperty<RecordDraftEntity>(
    _entities[2].properties[4],
  );

  /// See [RecordDraftEntity.payloadSchemaVersion].
  static final payloadSchemaVersion =
      obx.QueryIntegerProperty<RecordDraftEntity>(_entities[2].properties[5]);

  /// See [RecordDraftEntity.fieldPayloadJson].
  static final fieldPayloadJson = obx.QueryStringProperty<RecordDraftEntity>(
    _entities[2].properties[6],
  );

  /// See [RecordDraftEntity.baseLastModified].
  static final baseLastModified = obx.QueryDateProperty<RecordDraftEntity>(
    _entities[2].properties[7],
  );

  /// See [RecordDraftEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<RecordDraftEntity>(
    _entities[2].properties[8],
  );

  /// See [RecordDraftEntity.lastSavedAt].
  static final lastSavedAt = obx.QueryDateProperty<RecordDraftEntity>(
    _entities[2].properties[9],
  );
}

/// [AuthorProfileEntity] entity fields to define ObjectBox queries.
class AuthorProfileEntity_ {
  /// See [AuthorProfileEntity.id].
  static final id = obx.QueryIntegerProperty<AuthorProfileEntity>(
    _entities[3].properties[0],
  );

  /// See [AuthorProfileEntity.authorProfileId].
  static final authorProfileId = obx.QueryStringProperty<AuthorProfileEntity>(
    _entities[3].properties[1],
  );

  /// See [AuthorProfileEntity.nickname].
  static final nickname = obx.QueryStringProperty<AuthorProfileEntity>(
    _entities[3].properties[2],
  );

  /// See [AuthorProfileEntity.colorValue].
  static final colorValue = obx.QueryIntegerProperty<AuthorProfileEntity>(
    _entities[3].properties[3],
  );

  /// See [AuthorProfileEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<AuthorProfileEntity>(
    _entities[3].properties[4],
  );

  /// See [AuthorProfileEntity.isCurrent].
  static final isCurrent = obx.QueryBooleanProperty<AuthorProfileEntity>(
    _entities[3].properties[5],
  );
}

/// [DeviceProfileEntity] entity fields to define ObjectBox queries.
class DeviceProfileEntity_ {
  /// See [DeviceProfileEntity.id].
  static final id = obx.QueryIntegerProperty<DeviceProfileEntity>(
    _entities[4].properties[0],
  );

  /// See [DeviceProfileEntity.deviceProfileId].
  static final deviceProfileId = obx.QueryStringProperty<DeviceProfileEntity>(
    _entities[4].properties[1],
  );

  /// See [DeviceProfileEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<DeviceProfileEntity>(
    _entities[4].properties[2],
  );

  /// See [DeviceProfileEntity.isCurrent].
  static final isCurrent = obx.QueryBooleanProperty<DeviceProfileEntity>(
    _entities[4].properties[3],
  );

  /// See [DeviceProfileEntity.hasSharedHistory].
  static final hasSharedHistory = obx.QueryBooleanProperty<DeviceProfileEntity>(
    _entities[4].properties[4],
  );
}
