// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/activity_entity.dart';
import 'models/diary_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3014340625497478550),
    name: 'ActivityEntity',
    lastPropertyId: const obx_int.IdUid(6, 2147283445462106961),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4693112843845237037),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8664221998494237186),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 21500456046779489),
        name: 'time',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8818483730579662998),
        name: 'details',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4969781922129048019),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2147283445462106961),
        name: 'diaryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4296004632891135973),
        relationField: 'diary',
        relationTarget: 'DiaryEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7784148166755830454),
    name: 'DiaryEntity',
    lastPropertyId: const obx_int.IdUid(5, 6225454372744249316),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4920149699993225483),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5934905229092552166),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7334882726399196966),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3139534169329158746),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6225454372744249316),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 6838825628405302824),
        name: 'activities',
        targetId: const obx_int.IdUid(1, 3014340625497478550),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7784148166755830454),
    lastIndexId: const obx_int.IdUid(1, 4296004632891135973),
    lastRelationId: const obx_int.IdUid(1, 6838825628405302824),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ActivityEntity: obx_int.EntityDefinition<ActivityEntity>(
      model: _entities[0],
      toOneRelations: (ActivityEntity object) => [object.diary],
      toManyRelations: (ActivityEntity object) => {},
      getId: (ActivityEntity object) => object.id,
      setId: (ActivityEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ActivityEntity object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final detailsOffset = fbb.writeString(object.details);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addInt64(2, object.time.millisecondsSinceEpoch);
        fbb.addOffset(3, detailsOffset);
        fbb.addInt64(4, object.lastModified.millisecondsSinceEpoch);
        fbb.addInt64(5, object.diary.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final detailsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastModifiedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = ActivityEntity(
          id: idParam,
          type: typeParam,
          time: timeParam,
          details: detailsParam,
          lastModified: lastModifiedParam,
        );
        object.diary.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.diary.attach(store);
        return object;
      },
    ),
    DiaryEntity: obx_int.EntityDefinition<DiaryEntity>(
      model: _entities[1],
      toOneRelations: (DiaryEntity object) => [],
      toManyRelations: (DiaryEntity object) => {
        obx_int.RelInfo<DiaryEntity>.toMany(1, object.id): object.activities,
      },
      getId: (DiaryEntity object) => object.id,
      setId: (DiaryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DiaryEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.date.millisecondsSinceEpoch);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addInt64(4, object.lastModified.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastModifiedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = DiaryEntity(
          id: idParam,
          date: dateParam,
          title: titleParam,
          content: contentParam,
          lastModified: lastModifiedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<DiaryEntity>(
          object.activities,
          store,
          obx_int.RelInfo<DiaryEntity>.toMany(1, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ActivityEntity] entity fields to define ObjectBox queries.
class ActivityEntity_ {
  /// See [ActivityEntity.id].
  static final id = obx.QueryIntegerProperty<ActivityEntity>(
    _entities[0].properties[0],
  );

  /// See [ActivityEntity.type].
  static final type = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[1],
  );

  /// See [ActivityEntity.time].
  static final time = obx.QueryDateProperty<ActivityEntity>(
    _entities[0].properties[2],
  );

  /// See [ActivityEntity.details].
  static final details = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[3],
  );

  /// See [ActivityEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<ActivityEntity>(
    _entities[0].properties[4],
  );

  /// See [ActivityEntity.diary].
  static final diary = obx.QueryRelationToOne<ActivityEntity, DiaryEntity>(
    _entities[0].properties[5],
  );
}

/// [DiaryEntity] entity fields to define ObjectBox queries.
class DiaryEntity_ {
  /// See [DiaryEntity.id].
  static final id = obx.QueryIntegerProperty<DiaryEntity>(
    _entities[1].properties[0],
  );

  /// See [DiaryEntity.date].
  static final date = obx.QueryDateProperty<DiaryEntity>(
    _entities[1].properties[1],
  );

  /// See [DiaryEntity.title].
  static final title = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[2],
  );

  /// See [DiaryEntity.content].
  static final content = obx.QueryStringProperty<DiaryEntity>(
    _entities[1].properties[3],
  );

  /// See [DiaryEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<DiaryEntity>(
    _entities[1].properties[4],
  );

  /// see [DiaryEntity.activities]
  static final activities =
      obx.QueryRelationToMany<DiaryEntity, ActivityEntity>(
        _entities[1].relations[0],
      );
}
